import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";

import Header from "@/template/Header";
import Footer from "@/template/Footer";
import TanstacQueryProvider from "components/partials/providers/TanstacQueryProvider";
import localFont from "next/font/local";

const yekanFont = localFont({
  src: "../public/fonts/Yekan.woff2",
  display: "swap",
});

export const metadata = {
  title: "تورینو",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl" className={yekanFont.className}>
      <body>
        <TanstacQueryProvider>
          <Header />
          {children}
        </TanstacQueryProvider>
        <Footer />
        <ToastContainer position="top-right" autoClose={3000} theme="colored" />
      </body>
    </html>
  );
}
